### ISSUE TITLE
If the database is not reachable, seafile-server logs are misleading

### ISSUE THREAD

**Issue by christophdb** [datamate-rethink-it/seafile-release#39]
# How to reproduce:

install seafile and mariadb and make a mistake with DB_HOST. Then execute `docker logs seafile-server`. You will see as last entry:

```
2024-10-30 12:36:37 Reloading NGINX... 
```

This is misleading. There should be a log entry like: Try to connect to database...

**Comment by simonhammes** [comment]
This is caused by buffered I/O. It actually prints `waiting for mysql server to be ready` (https://github.com/haiwen/seafile-docker/blob/b5967dedf16acde7aa6feddb3dbd54f89162db6c/scripts/scripts_11.0/utils.py#L290), but the output is buffered.

2 solutions:
- Set `PYTHONUNBUFFERED=1` to disable buffered I/O
- Copy `utils.py` into this repository and use `print('...', flush=True)` to immediately flush (`utils.py` is imported by `setup-databases.py`)
