### ISSUE TITLE
mount background image and favicon via docker-compose.yml

### ISSUE THREAD

**Issue by christophdb** [datamate-rethink-it/seafile-release#7]
- test if this works.

how to deal on a cluster?

**Comment by simonhammes** [comment]
The following volume mounts should work:

```yml
- ./logo.jpg:/shared/seafile/seahub-data/custom/mylogo.png:ro
- ./logo.jpg:/shared/seafile/seahub-data/custom/favicon.ico:ro
- ./logo.jpg:/shared/seafile/seahub-data/custom/login-bg.jpg:ro
```

The container paths should not be modified since seahub is configured to access these paths: https://github.com/haiwen/seahub/blob/58e4e6624393d77ccb03cdb3c55843f52612faf6/seahub/settings.py#L607

Note: The files are moved/linked into seahub/... during container startup

**Comment by simonhammes** [comment]
Note to self: add this to `configuration.md`
